// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _insertMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchbyimageMw() []app.HandlerFunc {
	// your code...
	return nil
}
